packages:
  - apps/**/*
  - packages/*
  - packages/*/*
  - be
  - be/packages/*
  - be/apps/*

catalog:
  '@egoist/tailwindcss-icons': 1.9.2
  '@iconify-json/mingcute': 1.2.7
  '@t3-oss/env-core': 0.13.10
  '@tailwindcss/postcss': 4.1.18
  '@tailwindcss/typography': 0.5.19
  '@types/react': 19.2.14
  '@types/react-dom': 19.2.3
  dotenv-expand: 12.0.3
  motion: 12.34.0
  satori: 0.19.2
  tailwind-scrollbar: 4.0.2
  tailwind-variants: 3.2.2
  tailwindcss: 4.1.18
  tailwindcss-animate: 1.0.7
  tailwindcss-safe-area: 1.3.0
  tailwindcss-uikit-colors: 1.0.0
  typescript: 5.9.3
  zod: 4.3.6
